-- MySQL Script generated by MySQL Workbench
-- Sun May  5 14:17:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgrif
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgrif
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgrif` DEFAULT CHARACTER SET utf8 ;
USE `sgrif` ;

-- -----------------------------------------------------
-- Table `sgrif`.`equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`equipamento` (
  `idEquipamento` INT(11) NOT NULL auto_increment,
  `marca` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `config` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgrif`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`sala` (
  `idSala` INT(11) NOT NULL auto_increment,
  `nome` VARCHAR(255) NOT NULL,
  `localizacao` VARCHAR(255) NOT NULL,
  `capacidade` INT(11) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgrif`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`usuario` (
  `idUsuario` INT(11) NOT NULL auto_increment,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgrif`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`reserva` (
  `idReserva` INT(11) NOT NULL auto_increment,
  `idUsuario` INT(11) NOT NULL,
  `idSala` INT(11) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `dataReserva` DATE NOT NULL,
  `inicioReserva` DATE NOT NULL,
  `fimReserva` DATE NOT NULL,
  `periodicidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `Usuario_idUsuario` (`idUsuario` ASC),
  INDEX `fk_reserva_sala1_idx` (`idSala` ASC),
  CONSTRAINT `reserva_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgrif`.`usuario` (`idUsuario`),
  CONSTRAINT `fk_reserva_sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `sgrif`.`sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgrif`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`ocorrencia` (
  `idOcorrencia` INT NOT NULL auto_increment,
  `idReserva` INT(11) NOT NULL,
  `dia` DATE NOT NULL,
  `inicio` TIME NOT NULL,
  `fim` TIME NOT NULL,
  PRIMARY KEY (`idOcorrencia`),
  INDEX `fk_ocorrencia_reserva1_idx` (`idReserva` ASC),
  CONSTRAINT `fk_ocorrencia_reserva1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `sgrif`.`reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgrif`.`equipamento_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgrif`.`equipamento_sala` (
  `idSala` INT(11) NOT NULL auto_increment,
  `idEquipamento` INT(11) NOT NULL,
  `qtdeTotal` INT NOT NULL,
  `qtdeOperavel` INT NOT NULL,
  PRIMARY KEY (`idSala`, `idEquipamento`),
  INDEX `fk_sala_has_equipamento_equipamento1_idx` (`idEquipamento` ASC),
  INDEX `fk_sala_has_equipamento_sala1_idx` (`idSala` ASC),
  CONSTRAINT `fk_sala_has_equipamento_sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `sgrif`.`sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_has_equipamento_equipamento1`
    FOREIGN KEY (`idEquipamento`)
    REFERENCES `sgrif`.`equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
